[package]
name = "pwerus"
version = "0.0.1"
authors = ["Joe Banks <joseph@josephbanks.me>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
